-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 21:10:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projmorro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projmorro` ;

-- -----------------------------------------------------
-- Schema projmorro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projmorro` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `projmorro` ;

-- -----------------------------------------------------
-- Table `projmorro`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projmorro`.`aluno` ;

CREATE TABLE IF NOT EXISTS `projmorro`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(45) NOT NULL,
  `nome_completo` VARCHAR(60) NOT NULL,
  `tel_fixo` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NOT NULL,
  `alunocol` VARCHAR(45) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero_casa` VARCHAR(6) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `renda_familiar` FLOAT NULL,
  `foto` BLOB NULL,
  PRIMARY KEY (`idaluno`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projmorro`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projmorro`.`curso` ;

CREATE TABLE IF NOT EXISTS `projmorro`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `turno` ENUM('MANHÃ', 'TARDE', 'NOITE') NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projmorro`.`matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projmorro`.`matricula` ;

CREATE TABLE IF NOT EXISTS `projmorro`.`matricula` (
  `idmatricula` INT NOT NULL AUTO_INCREMENT,
  `aluno_idaluno` INT NOT NULL,
  `curso_idcurso` INT NOT NULL,
  PRIMARY KEY (`idmatricula`, `aluno_idaluno`, `curso_idcurso`),
  INDEX `fk_aluno_has_curso_curso1_idx` (`curso_idcurso` ASC) VISIBLE,
  INDEX `fk_aluno_has_curso_aluno_idx` (`aluno_idaluno` ASC) VISIBLE,
  UNIQUE INDEX `idmatricula_UNIQUE` (`idmatricula` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_has_curso_aluno`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `projmorro`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_curso_curso1`
    FOREIGN KEY (`curso_idcurso`)
    REFERENCES `projmorro`.`curso` (`idcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


